<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>promise的几个关键问题4</title>
	<script src="./js/jquery.js"></script>
</head>

<body>
	<script>
		//Promise如何串连多个异步任务? ---- 通过then的链式调用
		//#region 
		/* function sendAjax(url, data, index) {
			return new Promise((resolve, reject) => {
				//函数体
				//实例xhr
				const xhr = new XMLHttpRequest()
				// 绑定监听
				xhr.onreadystatechange = () => {
					if (xhr.readyState === 4) {
						if (xhr.status >= 200 && xhr.status <= 300) resolve(xhr.response);
						else reject(`第${index}次请求出了点问题`);
					}
				}
				//整理参数
				let str = ''
				for (let key in data) {
					str += `${key}=${data[key]}&`
				}
				str = str.slice(0, -1)
				xhr.open('GET', url + '?' + str)
				xhr.responseType = 'json'
				xhr.send()
			});

		}

		// 发送第一次请求
		sendAjax('https://api.apiopen.top/getJoke', {
				page: 1
			}, 1)
			.then(
				value => {
					console.log('第一次请求成功了', value);
					// 发送第二次请求
					return sendAjax('https://api.apiopen.top/getJoke2', {
						page: 1
					}, 2)
				},
				// reason => {
				// 	console.log(reason);
				// 	return new Promise(() => {})
				// }
			)
			.then(
				value => {
					console.log('第二次请求成功了', value);
					// 发送第三次请求
					return sendAjax('https://api.apiopen.top/getJoke', {
						page: 1
					}, 3)
				},
				// reason => {
				// 	console.log(reason);
				// 	return new Promise(() => {})
				// }
			)
			.then(
				value => {
					console.log('第三次请求成功了', value);
					// 发送第四次请求
					return sendAjax('https://api.apiopen.top/getJoke', {
						page: 1
					}, 4)
				},
				// reason => {
				// 	console.log(reason);
				// 	return new Promise(() => {})
				// }
			)
			.catch(
				reason => {
					console.log(reason);
					return new Promise(() => {})
				}
			) */
		//#endregion

		// 另一个例子演示错误的穿透
		const p = new Promise((resolve,reject)=>{
		  setTimeout(()=>{
			// resolve('z')
			reject(-1)
		  })
		},1000)

		p.then(
			value => {
				console.log('成功了1',value);
				return 'b'
			},
			// reason => {
			// 	console.log('失败了1',reason);
			// 	return -2
			// }
		)
		.then(
			value => {
				console.log('成功了2',value);
				return 'd'
			},
			// reason => {
			// 	console.log('失败了2',reason);
			// 	return -3
			// }
		)
		.then(
			value => {
				console.log('成功了3',value);
				return 'e'
			},
			// reason => {
			// 	console.log('失败了3',reason);
			// 	return -4
			// }
		)
		.catch(
			reason => {
				console.log('失败了',reason);
			}
		)

		p.then
	</script>
</body>

</html>